spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/razorpayDB
    username: postgres
    password: Singh@1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  kafka:
    listener:
      ack-mode: manual

    bootstrap-servers: localhost:29092

    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        retries: 3
        spring.json.add.type.headers: false

    consumer:
      group-id: razorpay-monolith
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.razorpay.*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: java.util.LinkedHashMap

  data:
    redis:
      host: localhost
      port: 6379

  threads:
    virtual:
      enabled: true


vault:
  master-key: MdUtNXxdrBCAkEYRuZ1UsDPbWk35H9kiCAl9/sBnDdc=


jwt:
  secret-key: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef


app:
  rate-limit:
    method: fixed
    requests-per-minute: 200
    window-seconds: 60

  kafka:
    topics:
      payment: payments.events
      order: orders.events
      refund: refund.events
      settlement: settlement.events


payment:
  simulator:
    poll-interval-ms: 5000
    chaos-mode: NORMAL

    methods:
      CARD:
        min-delay-seconds: 2
        max-delay-seconds: 6
        success-rate: 90

      UPI:
        min-delay-seconds: 1
        max-delay-seconds: 3
        success-rate: 95

      NET_BANKING:
        min-delay-seconds: 4
        max-delay-seconds: 10
        success-rate: 80


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    hostname: localhost


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  metrics:
    tags:
      application: ${spring.application.name}


logging:
  level:
    org.apache.kafka.client: WARN
    org.apache.kafka.common: WARN
